
def generate_header_and_body_tex(entries)
	entries << '\documentclass{article}'
	entries << '\usepackage[utf8]{inputenc}'
	entries << '\usepackage[T1]{fontenc}'
	entries << '\usepackage{microtype}'
	entries << '\usepackage{graphicx}'
	entries << '\usepackage{listings}'
	entries << '\usepackage{wrapfig}'
	entries << '\usepackage{enumitem}'
	entries << '\usepackage{balance}'
	entries << '\usepackage{float}'
	entries << '\usepackage{url}'
	entries << '\usepackage{tabularx}'
	entries << '\usepackage[table]{xcolor}'
	entries << '\usepackage{booktabs}'
	entries << '\usepackage{subfigure}'
	entries << '\usepackage{multirow}'
	entries << '\usepackage{mdframed}'
	entries << ''
	entries << '\title{test}'
	entries << '\author{srsj2 Sotero Jr}'
	entries << '\date{December 2018}'
	entries << ''
	entries << '\begin{document}'
	entries << ''
	entries << '\begin{tabular}{llrrr}'
	entries << '\toprule'
	entries << '\emph{Group} & \emph{Subject} & \multicolumn{1}{c}{$T_s$} & \multicolumn{1}{c}{$T_p$} & $T_s/T_p$ \\\\% '
	entries << '\midrule% '
end

def generate_footer_tex(entries,value,count)
	entries << '\midrule'
	entries << 'Average &  &  &  & ' + (value/count).round(2).to_s + ' \\\\'
	entries << '\bottomrule%'
	entries << '\end{tabular}'
	entries << ''
	entries << '\end{document}'
end
