#!/bin/bash

TEST_PATH="$1"
if [ -z "$TEST_PATH" ]; then
	echo "Usage: ./extract-timestamps <path to tests>"
	exit 1;
fi

BASEDIR="`pwd`"
cd "$TEST_PATH"

mvn test &> "$BASEDIR/mvn-log.txt"
cat "$BASEDIR/mvn-log.txt" | grep INFO: | sed "s/INFO: //g" > "$BASEDIR/timestamps.csv"
cd "$BASEDIR"
