#!/bin/bash

TEST_PATH="$1"
if [ -z "$TEST_PATH" ]; then
	echo "Usage: ./extract-timestamps <path to tests>"
	exit 1;
fi

BASEDIR="`pwd`"
cd "$TEST_PATH"

mvn test > "$BASEDIR/mvn-log.txt"

# The pattern "###" is a convenience to filter only the desired lines
# It is defined as "prefixPattern" in TestNGCustomRunner.onExecutionFinish() 
cat "$BASEDIR/mvn-log.txt" | grep "###" | sed "s/###//g" > "$BASEDIR/timestamps.csv"

cd "$BASEDIR"
